application: sharedhat-lab
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: app/assets/css

- url: /images
  static_dir: app/assets/images

- url: /.*
  script: sharedhat.py