application: sharedhat-lab
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: templates/assets/css

- url: /images
  static_dir: templates/assets/images

- url: /js
  static_dir: templates/assets/js

- url: /.*
  script: sharedhat.py

builtins:
- datastore_admin: on